# Generated by Django 4.1.1 on 2022-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="descripton",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
