# Generated by Django 4.1.1 on 2022-11-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_descripton"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="descripton",
            new_name="description",
        ),
    ]
