# Generated by Django 4.1.1 on 2022-11-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="experience",
            new_name="experiences",
        ),
    ]
